# Auto-merge configuration for Dependabot PRs
# Place this file at .github/auto-merge.yml in your repository

# Configure here which dependency updates should be merged automatically.
# The recommended configuration is the following:
- match:
    # Only merge patches for production dependencies
    dependency_type: production
    update_type: "semver:patch"
- match:
    # and development dependencies can have a minor update, too
    dependency_type: development
    update_type: "semver:minor"

# The syntax is based on the legacy dependabot v1 automerged_updates syntax, see:
# https://dependabot.com/docs/config-file/#automerged_updates

# Additional examples:

# Allow all patch updates (both production and development):
# - match:
#     update_type: "semver:patch"

# Allow all minor updates for development dependencies:
# - match:
#     dependency_type: development
#     update_type: "semver:minor"

# Allow major updates for specific development dependencies:
# - match:
#     dependency_type: development
#     update_type: "semver:major"
